@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Oct 15 14:32:27 -0700 2022
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim divider_4_top_simulation_tb_behav -key {Behavioral:sim_1:Functional:divider_4_top_simulation_tb} -tclbatch divider_4_top_simulation_tb.tcl -view C:/Users/scottsus/EE 354/Lab 9/Divider_Pico_N4_4bit/synthesis/divider_4_top_simulation_tb_behav.wcfg -log simulate.log"
call xsim  divider_4_top_simulation_tb_behav -key {Behavioral:sim_1:Functional:divider_4_top_simulation_tb} -tclbatch divider_4_top_simulation_tb.tcl -view C:/Users/scottsus/EE 354/Lab 9/Divider_Pico_N4_4bit/synthesis/divider_4_top_simulation_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
